### ISSUE TITLE
Clarification of Readme.md create Django local settings file

### ISSUE THREAD

**Issue by thormiwa** [creativecommons/cc-legal-tools-app#300]
## Problem
The step about the creation of django local settings file is vague. 
<img width="1385" alt="Screenshot 2022-10-10 at 19 57 34" src="https://user-images.githubusercontent.com/70862950/194934924-e8467fbd-1070-49dd-94a6-db56dc9a7b6e.png">

## Description
Adding a sub step that tells people how to change directory into the `cc-legal-tools-app` directory then running the command will help make it clearer

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by anjayluh** [comment]
Hi, I'm Angella from Outreachy and I'd like to take on this issue

**Comment by Emenyi95** [comment]
Hello @thormiwa . My name is Emenyi Nelly and I am an Outreach intern and I would love to work on this issue.

**Comment by yokwejuste** [comment]
Hey @thormiwa trust this meets you well?

I was asking by the way if help is needed? I can be of help on this,

@TimidRobot Can I be of help on this issue?
