### ISSUE TITLE
[Feature] Improving the legibility of the site content to enhance readibility

### ISSUE THREAD

**Issue by pragmaticAweds** [creativecommons/cc-legal-tools-app#307]
## Problem
Website content should be legible to increase readability in the user experience. This is an important aspect that also contributes to users staying or leaving the website.

I checked the website, and the first thing that caught my attention was the font size which was too small. This can prevent users with/without eye problems to read the content of the website. 

## Description

This is an image with the current font size which I think is not ideal.

<img width="1053" alt="Screenshot 2022-10-14 at 9 51 06 AM" src="https://user-images.githubusercontent.com/70960505/195807693-4ca1f14b-032c-4a99-8d87-9acd514b68c3.png">

My suggestion is to increase the font size to 14px or 16px for paragraphs and for titles it can be 16px with font-weight of 500.

## Alternatives
I also believe that using Arial or Roboto font family can improve the user experience.

## Implementation
 The implementation is quite simple:
- the paragraph font size can be increased to 14px.
- the title can be increased to 16px with a font weight of 500.

- [x] I would be interested in implementing this feature.

**Comment by dikehprosper** [comment]
@pragmaticAweds I think this issue was supposed to be created in the meta-search repository

**Comment by pragmaticAweds** [comment]
Oooops, thank you @dikehprosper  i have moved the issue there thank you.
