### ISSUE TITLE
[Bug] Improve Height of Aside Container 

### ISSUE THREAD

**Issue by ShivamAhir** [creativecommons/cc-legal-tools-app#422]
## Description
 The container housing the list of licenses extends from the top to the bottom of the page, resulting in poor visual appearance. This aspect requires adjustment to enhance the overall appearance and user experience.

## Reproduction

1. Click on this [link](https://legal-tools-dev.creativecommons.org/licenses/list.en)
2. See the website on laptop
3. See on the right side of the page

## Expectation
<img width="963" alt="Screenshot 2024-03-07 at 4 59 18 PM" src="https://github.com/creativecommons/cc-legal-tools-app/assets/74092725/ed6f9e24-c91e-4104-8236-ad97d76d2fc0">
<img width="963" alt="Screenshot 2024-03-07 at 4 59 00 PM" src="https://github.com/creativecommons/cc-legal-tools-app/assets/74092725/a4d5e0b3-4193-4547-85dd-a4837db33ca2">

## Screenshots
Currently it look like this on Laptops
<img width="961" alt="Screenshot 2024-03-07 at 4 59 35 PM" src="https://github.com/creativecommons/cc-legal-tools-app/assets/74092725/9c091c89-cadb-43a7-9564-ddeb5aadd9d1">
<img width="964" alt="Screenshot 2024-03-07 at 4 59 49 PM" src="https://github.com/creativecommons/cc-legal-tools-app/assets/74092725/2843185a-f721-4a00-b75e-0b6632f8f5bc">
<img width="961" alt="Screenshot 2024-03-07 at 5 00 02 PM" src="https://github.com/creativecommons/cc-legal-tools-app/assets/74092725/3293e676-5c90-486f-9a3e-338b0d78c066">
<img width="962" alt="Screenshot 2024-03-07 at 5 00 16 PM" src="https://github.com/creativecommons/cc-legal-tools-app/assets/74092725/dcad80f9-be5d-4465-a48a-e9f2c18a4213">

## Environment

 - Device: (laptop)
 - Browser: (_eg._ Safari; Firefox, Chrome)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by keshav861** [comment]
can i contribute in this

**Comment by ShivamAhir** [comment]
Hello, @keshav861. I am currently working on this. You can view the other issue.
